#!/bin/bash
echo "Betty Style Check \n"
betty $CFILE
echo "--------------------------------------\n"
echo "Compiling and running C code\n"
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 _putchar.c main.c $CFILE
./a.out | cat -e
